version: '2'

services:
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=postgres
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

volumes:
  redis_data:
    driver: local

networks:
  basic: