# Generated by Django 3.1.7 on 2021-04-23 10:38

import basedb.storage
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('NewsTitle', models.CharField(max_length=150, verbose_name='文章标题')),
                ('NewsText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='文章详情')),
                ('in_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('images', models.ImageField(blank=True, null=True, storage=basedb.storage.ImageStorage(), upload_to='website/images', verbose_name='封面图片')),
                ('file', models.FileField(blank=True, null=True, storage=basedb.storage.ImageStorage(), upload_to='website/files', verbose_name='附件')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='NewsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('group', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='分组')),
                ('NewsClassName', models.CharField(default='未设置', max_length=100, verbose_name='文章分类')),
                ('images', models.ImageField(blank=True, null=True, storage=basedb.storage.ImageStorage(), upload_to='website/images', verbose_name='封面图片')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='SinglePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('code', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='调用代码')),
                ('NewsTitle', models.CharField(max_length=150, verbose_name='文章标题')),
                ('NewsText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='文章详情')),
                ('in_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('images', models.ImageField(blank=True, null=True, storage=basedb.storage.ImageStorage(), upload_to='website/images', verbose_name='封面图片')),
                ('file', models.FileField(blank=True, null=True, storage=basedb.storage.ImageStorage(), upload_to='website/files', verbose_name='附件')),
            ],
            options={
                'verbose_name': '单页',
                'verbose_name_plural': '单页',
            },
        ),
    ]
