# Generated by Django 3.1.7 on 2021-04-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactive',
            name='active_count',
        ),
        migrations.RemoveField(
            model_name='interactive',
            name='status',
        ),
        migrations.AddField(
            model_name='interactive',
            name='ask_count',
            field=models.IntegerField(default=1, verbose_name='咨询次数'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='response_count',
            field=models.IntegerField(default=0, verbose_name='回答次数'),
        ),
        migrations.AlterField(
            model_name='servetype',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bellow_section', to='basedb.sectiontype', verbose_name='所属部门'),
        ),
    ]
