# Generated by Django 3.1.7 on 2021-04-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0002_auto_20210423_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontype',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedb.sectiontype', verbose_name='上级部门'),
        ),
    ]
