# Generated by Django 3.1.7 on 2021-04-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0004_auto_20210423_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_url',
            field=models.CharField(max_length=200, verbose_name='上传文件'),
        ),
    ]
