# Generated by Django 3.1.7 on 2021-04-24 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0005_auto_20210423_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='项目合同'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_person',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('0', '用户草稿'), ('1', '待审核'), ('2', '竞标中'), ('3', '选标中'), ('4', '已选标'), ('5', '结束'), ('6', '作废')], default='0', max_length=3, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='proprietorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietor_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
