# Generated by Django 3.1.7 on 2021-04-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0006_auto_20210424_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proprietor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_proprietor', to='basedb.proprietorprofile', verbose_name='业主'),
        ),
    ]
