# Generated by Django 3.1.7 on 2021-04-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0007_auto_20210424_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='bid_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_project_intermediary', to='basedb.intermediaryprofile'),
        ),
    ]
