# Generated by Django 3.1.7 on 2021-04-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0011_auto_20210424_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidproject',
            name='status',
            field=models.CharField(choices=[('0', '已投标'), ('1', '中标')], default='0', max_length=2, verbose_name='竞标状态'),
        ),
        migrations.AlterField(
            model_name='proprietorprofile',
            name='organization_picture',
            field=models.JSONField(blank=True, max_length=200, verbose_name='证件图片'),
        ),
        migrations.AlterField(
            model_name='proprietorprofile',
            name='status',
            field=models.CharField(choices=[('0', '草稿'), ('1', '待审核'), ('2', '已审核'), ('3', '驳回')], default='0', max_length=3, verbose_name='状态'),
        ),
    ]
