# Generated by Django 3.1.7 on 2021-04-24 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0013_auto_20210424_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_scale',
            field=models.IntegerField(verbose_name='项目规模'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_high_count',
            field=models.IntegerField(verbose_name='服务金额上限'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_low_count',
            field=models.IntegerField(verbose_name='服务金额下限'),
        ),
    ]
