# Generated by Django 3.1.7 on 2021-04-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0014_auto_20210424_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='files_info',
            field=models.JSONField(blank=True, null=True, verbose_name='竞标文件'),
        ),
        migrations.AlterField(
            model_name='bidproject',
            name='bid_money',
            field=models.IntegerField(verbose_name='竞标金额'),
        ),
    ]
