# Generated by Django 3.1.7 on 2021-04-25 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0016_auto_20210425_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='bid_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_bid_users', to=settings.AUTH_USER_MODEL, verbose_name='竞标人员'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_bid_projects', to='basedb.project', verbose_name='竞标的项目'),
        ),
    ]
