# Generated by Django 3.1.7 on 2021-04-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0017_auto_20210425_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='average_score',
            field=models.FloatField(default=0, verbose_name='平均分'),
        ),
        migrations.AddField(
            model_name='project',
            name='server_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedb.servetype', verbose_name='所属服务类型'),
        ),
        migrations.AlterField(
            model_name='bidproject',
            name='score_level_five',
            field=models.IntegerField(default=0, verbose_name='五级服务评价'),
        ),
        migrations.AlterField(
            model_name='bidproject',
            name='score_level_four',
            field=models.IntegerField(default=0, verbose_name='四级服务评价'),
        ),
        migrations.AlterField(
            model_name='bidproject',
            name='score_level_three',
            field=models.IntegerField(default=0, verbose_name='三级服务评价'),
        ),
        migrations.AlterField(
            model_name='bidproject',
            name='score_level_two',
            field=models.IntegerField(default=0, verbose_name='二级服务评价'),
        ),
    ]
