# Generated by Django 3.1.7 on 2021-04-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0019_auto_20210425_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='bidproject',
            name='owner_response',
            field=models.JSONField(default=list, verbose_name='业主回复'),
        ),
    ]
