# Generated by Django 3.1.7 on 2021-04-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0020_auto_20210426_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidproject',
            name='update_number',
        ),
    ]
