# Generated by Django 3.1.7 on 2021-04-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0021_auto_20210426_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUserModel',
            fields=[
            ],
            options={
                'verbose_name': '超级管理员',
                'verbose_name_plural': '超级管理员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('basedb.user',),
        ),
        migrations.RemoveField(
            model_name='bidproject',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='bidproject',
            name='owner_response',
        ),
        migrations.RemoveField(
            model_name='bidproject',
            name='score_level_five',
        ),
        migrations.RemoveField(
            model_name='bidproject',
            name='score_level_four',
        ),
        migrations.RemoveField(
            model_name='bidproject',
            name='score_level_one',
        ),
        migrations.RemoveField(
            model_name='bidproject',
            name='score_level_three',
        ),
        migrations.RemoveField(
            model_name='bidproject',
            name='score_level_two',
        ),
        migrations.AddField(
            model_name='project',
            name='average_score',
            field=models.FloatField(default=0, verbose_name='平均分'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_response',
            field=models.JSONField(default=list, verbose_name='业主回复'),
        ),
        migrations.AddField(
            model_name='project',
            name='score_level_five',
            field=models.IntegerField(default=0, verbose_name='五级服务评价'),
        ),
        migrations.AddField(
            model_name='project',
            name='score_level_four',
            field=models.IntegerField(default=0, verbose_name='四级服务评价'),
        ),
        migrations.AddField(
            model_name='project',
            name='score_level_one',
            field=models.IntegerField(default=0, verbose_name='一级服务评价'),
        ),
        migrations.AddField(
            model_name='project',
            name='score_level_three',
            field=models.IntegerField(default=0, verbose_name='三级服务评价'),
        ),
        migrations.AddField(
            model_name='project',
            name='score_level_two',
            field=models.IntegerField(default=0, verbose_name='二级服务评价'),
        ),
    ]
