# Generated by Django 3.1.7 on 2021-04-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0023_auto_20210427_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.JSONField(blank=True, default=None, max_length=200, null=True, verbose_name='项目合同'),
        ),
    ]
