# Generated by Django 3.1.7 on 2021-04-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0024_auto_20210427_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediaryprofile',
            name='enterprise_type',
            field=models.CharField(blank=True, choices=[('0', '其他'), ('1', '社会'), ('2', '事业单位'), ('3', '政府机构')], max_length=3, null=True, verbose_name='机构类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='funds_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='资金来源'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_scale',
            field=models.IntegerField(verbose_name='预算金额'),
        ),
    ]
