# Generated by Django 3.1.7 on 2021-04-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedb', '0027_auto_20210428_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediaryprofile',
            name='super_rate',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='上级评分'),
        ),
    ]
